#!/bin/bash
# Resolve repo-relative include paths so the script keeps working after moving the workspace.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OPENHITLS_DIR="$(cd "$ROOT_DIR/../openHiTLS" && pwd)"

exec gcc -C -E -DOPENHITLSDIR=\"/usr/local/\" \
  -I"$OPENHITLS_DIR/bsl/log/include" \
  -I"$OPENHITLS_DIR/config/macro_config" \
  -I"$OPENHITLS_DIR/bsl/err/include" \
  -I"$OPENHITLS_DIR/include/bsl" \
  -I"$OPENHITLS_DIR/bsl/include" \
  -I"$OPENHITLS_DIR/include/crypto" \
  -I"$OPENHITLS_DIR/crypto/include" \
  -I"$OPENHITLS_DIR/bsl/sal/include" \
  -I"$OPENHITLS_DIR/platform/Secure_C/include" \
  -I"$OPENHITLS_DIR/crypto/bn/include" \
  -I"$OPENHITLS_DIR/tls/include" \
  -I"$OPENHITLS_DIR/include/tls" \
  -I"$OPENHITLS_DIR/include/pki" \
  -I"$OPENHITLS_DIR/include/auth" \
  -D_FORTIFY_SOURCE=2 -O2 -pipe -Werror -Wextra -Wcast-qual -Wall -Wdate-time -Wfloat-equal -Wshadow -Wformat=2 -Wno-stringop-overread \
  -fsigned-char -fno-common -fno-strict-aliasing -fno-omit-frame-pointer -fPIC -fstack-protector-strong --param=ssp-buffer-size=4 \
  -DHITLS_CRYPTO_NIST_ECC_ACCELERATE -DHITLS_CRYPTO_BN_COMBA -DHITLS_CRYPTO_AES_PRECALC_TABLES -DHITLS_AARCH64_PACIASP -DHITLS_CRYPTO_SM2_PRECOMPUTE_512K_TBL \
  -DHITLS_AUTH -DHITLS_AUTH_PRIVPASS_TOKEN -DHITLS_BSL -DHITLS_BSL_ASN1 -DHITLS_BSL_BASE64 -DHITLS_BSL_BUFFER -DHITLS_BSL_CONF -DHITLS_BSL_HASH -DHITLS_BSL_LIST \
  -DHITLS_BSL_LOG -DHITLS_BSL_OBJ -DHITLS_BSL_PARAMS -DHITLS_BSL_PEM -DHITLS_BSL_PRINT -DHITLS_BSL_SAL -DHITLS_BSL_SAL_DL -DHITLS_BSL_SAL_FILE -DHITLS_BSL_SAL_LINUX \
  -DHITLS_BSL_SAL_LOCK -DHITLS_BSL_SAL_MEM -DHITLS_BSL_SAL_NET -DHITLS_BSL_SAL_STR -DHITLS_BSL_SAL_THREAD -DHITLS_BSL_SAL_TIME -DHITLS_BSL_TLV -DHITLS_BSL_UI \
  -DHITLS_BSL_UIO_BUFFER -DHITLS_BSL_UIO_FILE -DHITLS_BSL_UIO_MEM -DHITLS_BSL_UIO_PLT -DHITLS_BSL_UIO_TCP -DHITLS_BSL_UIO_UDP -DHITLS_CRYPTO -DHITLS_CRYPTO_CIPHER \
  -DHITLS_CRYPTO_CODECS -DHITLS_CRYPTO_CODECSKEY -DHITLS_CRYPTO_DRBG -DHITLS_CRYPTO_EALINIT -DHITLS_CRYPTO_ENTROPY -DHITLS_CRYPTO_HPKE -DHITLS_CRYPTO_KDF -DHITLS_CRYPTO_MAC \
  -DHITLS_CRYPTO_MD -DHITLS_CRYPTO_MODES -DHITLS_CRYPTO_PKEY -DHITLS_CRYPTO_PROVIDER -DHITLS_PKI -DHITLS_PKI_INFO -DHITLS_PKI_PKCS12 -DHITLS_PKI_X509 -DHITLS_SIXTY_FOUR_BITS \
  -DHITLS_TLS -DHITLS_TLS_CALLBACK -DHITLS_TLS_CONFIG -DHITLS_TLS_CONNECTION -DHITLS_TLS_FEATURE -DHITLS_TLS_HOST -DHITLS_TLS_MAINTAIN -DHITLS_TLS_PROTO_VERSION \
  -DHITLS_TLS_SUITE -DHITLS_TLS_SUITE_AUTH -DHITLS_TLS_SUITE_CIPHER -DHITLS_TLS_SUITE_KX -DOPENHITLS_VERSION_S='"openHiTLS 0.2.0 15 May 2025"' -DOPENHITLS_VERSION_I=2097152 \
  -D__FILENAME__='"$(notdir $(subst .o,,$@))"' \
  "$@"
